/** @file m_registers.h */

#ifndef M_COMP_REGISTERS_H
#define M_COMP_REGISTERS_H

#define M_COMP_REGISTERS_R0 0
#define M_COMP_REGISTERS_R1 1
#define M_COMP_REGISTERS_R2 2
#define M_COMP_REGISTERS_R3 3
#define M_COMP_REGISTERS_R4 4
#define M_COMP_REGISTERS_R5 5
#define M_COMP_REGISTERS_R6 6
#define M_COMP_REGISTERS_R7 7
#define M_COMP_REGISTERS_PC 8
#define M_COMP_REGISTERS_SP 9
#define M_COMP_REGISTERS_IR 10
#define M_COMP_REGISTERS_AC 11
#define M_COMP_REGISTERS_SR 12
#define M_COMP_REGISTERS_MDR 13
#define M_COMP_REGISTERS_MAR 14

#define M_COMP_REGISTERS_R0_NAME "R0"
#define M_COMP_REGISTERS_R1_NAME "R1"
#define M_COMP_REGISTERS_R2_NAME "R2"
#define M_COMP_REGISTERS_R3_NAME "R3"
#define M_COMP_REGISTERS_R4_NAME "R4"
#define M_COMP_REGISTERS_R5_NAME "R5"
#define M_COMP_REGISTERS_R6_NAME "R6"
#define M_COMP_REGISTERS_R7_NAME "R7"
#define M_COMP_REGISTERS_PC_NAME "PC"
#define M_COMP_REGISTERS_SP_NAME "SP"
#define M_COMP_REGISTERS_IR_NAME "IR"
#define M_COMP_REGISTERS_AC_NAME "AC"
#define M_COMP_REGISTERS_SR_NAME "SR"
#define M_COMP_REGISTERS_MDR_NAME "MDR"
#define M_COMP_REGISTERS_MAR_NAME "MAR"

#endif /* M_COMP_REGISTER_H */