/** @file cs3_signals.h */

#ifndef CS3_SIGNALS_H
#define CS3_SIGNALS_H

#define CS3_SIGNAL_ALU_S  CS_SIGNAL_IMPL_SPECIFIC_0
#define CS3_SIGNAL_ALU_R  CS_SIGNAL_IMPL_SPECIFIC_1
#define CS3_SIGNAL_ALU_TA CS_SIGNAL_IMPL_SPECIFIC_2
#define CS3_SIGNAL_ALU_TB CS_SIGNAL_IMPL_SPECIFIC_3

#endif /* CS3_SIGNALS_H */
